import { ScenarioModel } from "../types/scenario";

export const discoverOfferActivationScenario: ScenarioModel = {
  id: "scenario_discover_offer_activation_failure",
  title: "Offer Activation Failure / Discover Eligibility Issue",
  difficulty: "medium",
  incidentType: "business_logic_failure",
  rootCauseDomain: "product_config",
  summary: "Offer activation begins failing for Discover users after a quarter transition introduces invalid or mismatched eligibility configuration.",
  serviceContext: {
    primaryService: "offers-api",
    affectedPlatforms: ["iOS", "Android"],
    environment: "production",
    ownerTeam: "offers-team",
  },
  windowHint: {
    start: "2026-06-07T16:00:00Z",
    durationMinutes: 25,
    timezone: "UTC",
  },
  severityHint: {
    severity: "SEV2",
  },
  learningObjectives: [
    "Differentiate healthy API infrastructure from business logic failures",
    "Use status codes and logs to identify activation rejection patterns",
    "Segment impact by product type to identify Discover-only failures",
    "Escalate to the product or offers configuration owner rather than platform infrastructure",
  ],
  initialFacts: [
    {
      id: "fact_1",
      statement: "Users can see offers in the app, but some cannot activate them.",
      source: "briefing",
    },
    {
      id: "fact_2",
      statement: "Reports cluster around a subset of cardholders rather than all users.",
      source: "briefing",
    },
  ],
  discoverableFacts: [
    {
      id: "fact_3",
      statement: "Overall API success remains healthy while activation-specific failures rise.",
      source: "investigation",
    },
    {
      id: "fact_4",
      statement: "403 responses and business-rule errors increase for Discover activations.",
      source: "investigation",
    },
    {
      id: "fact_5",
      statement: "Visa and Mastercard remain healthy, pointing to product segmentation or config issues.",
      source: "investigation",
    },
  ],
  signals: [
    {
      id: "signal_1",
      category: "metric",
      name: "api success rate",
      expectation: "healthy",
      details: "Overall API success, latency, and throughput remain normal.",
    },
    {
      id: "signal_2",
      category: "metric",
      name: "activation 403 responses",
      expectation: "spikes",
      details: "Activation endpoint returns more 403 responses over time.",
    },
    {
      id: "signal_3",
      category: "log",
      name: "eligibility and offer code errors",
      expectation: "spikes",
      details: "Logs show offer_code_invalid, offer_not_eligible, and invalid_offer_period.",
    },
    {
      id: "signal_4",
      category: "configuration",
      name: "quarter transition",
      expectation: "isolated",
      details: "The timing aligns with a product configuration transition.",
    },
  ],
  signalParameters: [
    {
      type: "success_rate_drop",
      metric: "api_success_rate",
      from: 98.3,
      to: 97.2,
      durationMinutes: 20,
    },
    {
      type: "success_rate_drop",
      metric: "activation_success_rate",
      from: 96.8,
      to: 57.8,
      durationMinutes: 20,
    },
    {
      type: "status_code_spike",
      statusCode: 403,
      baseline: 9,
      peak: 172,
      durationMinutes: 20,
    },
    {
      type: "segment_impact",
      dimension: "product_type",
      affected: ["Discover"],
      unaffected: ["Visa", "Mastercard"],
      baselinePercent: 98.0,
      impactedPercent: 44.9,
    },
    {
      type: "segment_impact",
      dimension: "card_segment",
      affected: ["Discover Cashback"],
      unaffected: ["Visa Everyday"],
      baselinePercent: 98.1,
      impactedPercent: 42.7,
    },
    {
      type: "log_pattern",
      service: "offers-api",
      level: "ERROR",
      message: "activation rejected: offer_code_invalid for Discover user",
      trend: "spiking",
      attributes: {
        productType: "Discover",
        offerId: "DISC-Q3-5PCT",
        activationStatus: "rejected",
        statusCode: 403,
        errorCode: "offer_code_invalid",
      },
    },
    {
      type: "log_pattern",
      service: "offers-api",
      level: "ERROR",
      message: "eligibility mismatch during quarter transition",
      trend: "spiking",
      attributes: {
        productType: "Discover",
        offerId: "DISC-Q3-5PCT",
        activationStatus: "rejected",
        statusCode: 403,
        errorCode: "offer_not_eligible",
      },
    },
    {
      type: "log_pattern",
      service: "offers-api",
      level: "WARN",
      message: "invalid offer period detected on activation request",
      trend: "spiking",
      attributes: {
        productType: "Discover",
        offerId: "DISC-Q3-5PCT",
        activationStatus: "rejected",
        statusCode: 403,
        errorCode: "invalid_offer_period",
      },
    },
    {
      type: "request_outcome",
      service: "offers-api",
      method: "POST",
      route: "/v1/offers/activate",
      status: "ok",
      statusCode: 403,
      durationMs: 214,
      attributes: {
        productType: "Discover",
        ruleResult: "rejected",
      },
    },
  ],
  affectedSegments: [
    {
      dimension: "product_type",
      affected: ["Discover"],
      unaffected: ["Visa", "Mastercard"],
      notes: "The failure isolates to one product family.",
    },
    {
      dimension: "card_segment",
      affected: ["Discover Cashback"],
      unaffected: ["Visa Everyday"],
      notes: "A narrower business segment also shows the issue.",
    },
  ],
  timelineHints: [
    {
      id: "marker_1",
      minuteOffset: 2,
      label: "Quarter transition configuration begins",
      category: "investigation",
    },
    {
      id: "marker_2",
      minuteOffset: 10,
      label: "Discover activation failures appear",
      category: "symptom",
    },
    {
      id: "marker_3",
      minuteOffset: 12,
      label: "403 spike observed on activation endpoint",
      category: "impact",
    },
    {
      id: "marker_4",
      minuteOffset: 14,
      label: "Product segmentation identifies Discover-only failures",
      category: "cause",
    },
  ],
  expectedEvidence: ["api_health", "status_codes", "business_rule_logs", "traces", "segment_breakdown", "config_marker"],
  expectedActions: [
    {
      type: "investigate",
      owner: "mobile_engineer",
      description: "Confirm the problem is activation-specific rather than a general offers outage.",
    },
    {
      type: "correlate",
      owner: "mobile_engineer",
      description: "Correlate 403 spikes with product segmentation and business-rule errors.",
    },
    {
      type: "escalate",
      owner: "offers_team",
      description: "Escalate to the offers or product configuration owner for eligibility review.",
    },
  ],
};
