import { ScenarioModel } from "../types/scenario";

export const mobileEnumMappingScenario: ScenarioModel = {
  id: "scenario_mobile_enum_mapping_failure",
  title: "Mobile Release Enum Mapping / Decoding Issue",
  difficulty: "medium",
  incidentType: "client_regression",
  rootCauseDomain: "mobile_client",
  summary: "A new API enum value is returned successfully, but one mobile app version cannot decode it and hides a feature tile.",
  serviceContext: {
    primaryService: "rewards-api",
    affectedPlatforms: ["iOS", "Android"],
    environment: "production",
    ownerTeam: "ios-team",
  },
  windowHint: {
    start: "2026-06-07T15:00:00Z",
    durationMinutes: 25,
    timezone: "UTC",
  },
  severityHint: {
    severity: "SEV2",
  },
  learningObjectives: [
    "Separate healthy API behavior from client-side rendering failures",
    "Use logs to identify enum decoding or mapping failures",
    "Narrow impact to a platform and app-version segment",
    "Escalate to the mobile client owner rather than backend infrastructure",
  ],
  initialFacts: [
    {
      id: "fact_1",
      statement: "Users report that the rewards tile is missing or failing to load.",
      source: "briefing",
    },
    {
      id: "fact_2",
      statement: "The backend API appears mostly healthy at a high level.",
      source: "briefing",
    },
  ],
  discoverableFacts: [
    {
      id: "fact_3",
      statement: "API success rate remains near normal while feature tile failure rate climbs.",
      source: "investigation",
    },
    {
      id: "fact_4",
      statement: "Failure logs cluster around enum decoding and unknown case handling.",
      source: "investigation",
    },
    {
      id: "fact_5",
      statement: "The issue is isolated to iOS 6.5.0 rather than all clients.",
      source: "investigation",
    },
  ],
  signals: [
    {
      id: "signal_1",
      category: "metric",
      name: "api success rate",
      expectation: "healthy",
      details: "The API continues returning mostly successful responses.",
    },
    {
      id: "signal_2",
      category: "metric",
      name: "feature tile failure rate",
      expectation: "spikes",
      details: "Feature-specific failures increase over time.",
    },
    {
      id: "signal_3",
      category: "log",
      name: "enum decoding failures",
      expectation: "spikes",
      details: "Logs include unknown enum values and mapping failures.",
    },
    {
      id: "signal_4",
      category: "release",
      name: "release ramp",
      expectation: "isolated",
      details: "Impact aligns with a new iOS app version rollout.",
    },
  ],
  signalParameters: [
    {
      type: "success_rate_drop",
      metric: "api_success_rate",
      from: 99.3,
      to: 98.7,
      durationMinutes: 20,
    },
    {
      type: "success_rate_drop",
      metric: "feature_tile_success_rate",
      from: 97.8,
      to: 61.4,
      durationMinutes: 20,
    },
    {
      type: "segment_impact",
      dimension: "platform",
      affected: ["iOS"],
      unaffected: ["Android"],
      baselinePercent: 98.9,
      impactedPercent: 63.2,
    },
    {
      type: "segment_impact",
      dimension: "app_version",
      affected: ["6.5.0"],
      unaffected: ["6.4.1"],
      baselinePercent: 98.3,
      impactedPercent: 61.4,
    },
    {
      type: "log_pattern",
      service: "ios-app",
      level: "ERROR",
      message: "rewards_tile mapping_failed for response payload",
      trend: "spiking",
      attributes: {
        feature: "rewards_tile",
        eventName: "mapping_failed",
        errorType: "enum_decoding_failed",
        unknownValue: "cash_boost_plus",
        appVersion: "6.5.0",
        osVersion: "18.0",
        platform: "iOS",
      },
    },
    {
      type: "log_pattern",
      service: "ios-app",
      level: "ERROR",
      message: "rewards_tile tile_failed and hidden after decoding error",
      trend: "spiking",
      attributes: {
        feature: "rewards_tile",
        eventName: "tile_failed",
        errorType: "enum_decoding_failed",
        unknownValue: "cash_boost_plus",
        appVersion: "6.5.0",
        osVersion: "18.0",
        platform: "iOS",
      },
    },
    {
      type: "request_outcome",
      service: "rewards-api",
      method: "GET",
      route: "/v1/rewards/home",
      status: "ok",
      statusCode: 200,
      durationMs: 182,
      attributes: {
        responseField: "cash_boost_plus",
      },
    },
  ],
  affectedSegments: [
    {
      dimension: "platform",
      affected: ["iOS"],
      unaffected: ["Android"],
      notes: "Android remains healthy while iOS carries the failure.",
    },
    {
      dimension: "app_version",
      affected: ["6.5.0"],
      unaffected: ["6.4.1"],
      notes: "The newest iOS release is disproportionately impacted.",
    },
    {
      dimension: "os_version",
      affected: ["18.0"],
      unaffected: ["17.6"],
      notes: "Observed alongside the impacted app version segment.",
    },
  ],
  timelineHints: [
    {
      id: "marker_1",
      minuteOffset: 3,
      label: "iOS 6.5.0 release ramp begins",
      category: "investigation",
    },
    {
      id: "marker_2",
      minuteOffset: 10,
      label: "Rewards tile failures increase",
      category: "symptom",
    },
    {
      id: "marker_3",
      minuteOffset: 12,
      label: "Logs show enum decoding failures for rewards_tile",
      category: "cause",
    },
    {
      id: "marker_4",
      minuteOffset: 15,
      label: "Issue appears isolated to iOS 6.5.0 users",
      category: "impact",
    },
  ],
  expectedEvidence: ["api_health", "feature_logs", "traces", "segment_breakdown", "release_marker"],
  expectedActions: [
    {
      type: "investigate",
      owner: "mobile_engineer",
      description: "Inspect feature-specific logs for decoding or mapping failures.",
    },
    {
      type: "confirm_scope",
      owner: "mobile_engineer",
      description: "Confirm the issue is limited to a platform and app-version segment.",
    },
    {
      type: "escalate",
      owner: "ios_team",
      description: "Escalate to the iOS client owner because backend health remains normal.",
    },
  ],
};
